/**
 * Types of financial reports available
 */
export enum ReportType {
  REVENUE_BY_PERIOD = 'REVENUE_BY_PERIOD',
  REVENUE_BY_SERVICE = 'REVENUE_BY_SERVICE',
  OUTSTANDING_INVOICES = 'OUTSTANDING_INVOICES',
  PAYMENT_COLLECTION = 'PAYMENT_COLLECTION',
  INSURANCE_CLAIM_STATUS = 'INSURANCE_CLAIM_STATUS',
}
